### ISSUE TITLE
Загрузка классов java ClassLoader

### ISSUE THREAD

**Issue by PantyukhinAleksey** [neooleg/selenide-for-c-sharp#2]
Указанный метод инициализации Java машины:
  private static void ConfigureJni4NetSelenide()
        {
            var bridgeSetup = new BridgeSetup();
            bridgeSetup.Verbose = true;
            bridgeSetup.AddAllJarsClassPath(".");
            bridgeSetup.IgnoreJavaHome = true;
            Bridge.CreateJVM(bridgeSetup);
            Bridge.RegisterAssembly(typeof(com.codeborne.selenide.Selenide).Assembly);
        }
оказался не рабочим. 

При регистрации библиотеки падает ошибка загрузки java-класса
Метод выдал исключение: net.sf.jni4net.jni.JNIException: Can't load java class for com.codeborne.selenide.CollectionCondition from classLoader sun.misc.Launcher$AppClassLoader@9931f5 ---> java.lang.ClassNotFoundException: com.codeborne.selenide.CollectionCondition.
Result StackTrace:  
java.net.URLClassLoader$1.run() :-1
    java.net.URLClassLoader$1.run() :-1
    java.security.AccessController.doPrivileged() :-2
    java.net.URLClassLoader.findClass() :-1
    java.lang.ClassLoader.loadClass() :-1
    sun.misc.Launcher$AppClassLoader.loadClass() :-1
    java.lang.ClassLoader.loadClass() :-1
   в net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   в net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
   в java.lang.ClassLoader.loadClass(String par0)
   в net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
 --- Конец трассировки стека внутреннего исключения ---
    в net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   в net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   в net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   в net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   в net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   в net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   в net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   в UnitTestProject1.UnitTest1.ConfigureJni4NetSelenide() в d:\TFSProject\UnitTestProject1\UnitTestProject1\UnitTest1.cs:строка 38
   в UnitTestProject1.UnitTest1.TestMethod1() в d:\TFSProject\UnitTestProject1\UnitTestProject1\UnitTest1.cs:строка 20

Нужна помощь в решении проблемы. Связаться можно в скайпе pantyhin_aleksey.
Жду выхода на связь.

**Comment by neooleg** [comment]
Hey Aleksey,

It seems, there is versions incompatibility issue between proxies and Selenide lib, so need to regenerate the proxies. Anyway, it's need to investigate with all details about versions, env, etc.
OK, we'll contact you.

**Comment by neooleg** [comment]
Have tried from scratch on another environment, so issue didn't appear.
